CREATE TABLE banks (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bank_name VARCHAR2(100),
    abbreviation VARCHAR2(10),
    app_code VARCHAR2(100),
    country VARCHAR2(50),
    PRIMARY KEY (bank_id)
);

CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    review VARCHAR2(1000),
    rating NUMBER,
    review_date DATE,
    bank_id NUMBER,
    source VARCHAR2(100),
    detected_language VARCHAR2(10),
    distilbert_sentiment VARCHAR2(20),
    FOREIGN KEY (bank_id) REFERENCES banks(bank_id)
);
